src/dex/urls.py
'''
Created on Apr 8, 2013

@author: mbianchini
'''
from dex.models.example import Example
from django.conf.urls import patterns, url
from django.views.generic.list import ListView

urlpatterns = patterns('',
    url(r'^browse/examples/$',
        ListView.as_view(
            queryset=Example.objects.all()[:5],
            context_object_name='examples',
            template_name='dex/example/browse.html'),
        name='browse'),
                       
    url(r'^show/example/(?P<example_id>\d+)$', 'dex.views.example.show', name='show'),      
    url(r'^update/example/(?P<example_id>\d+)$', 'dex.views.example.edit_update', name='update'),                         
)

src/django_examples/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
     url(r'^dex/', include('dex.urls', namespace="dex")),
     url(r'^comments/', include('comments.urls', namespace="comments")),
    # Examples:
    # url(r'^$', 'django_examples.views.home', name='home'),
    # url(r'^django_examples/', include('django_examples.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
     url(r'^admin/', include(admin.site.urls)),
)

src/core_examples/models/example.py
from core_examples.models.group import OrganizationGroup
from core_examples.models.user import User
from django.db import models

class Example(models.Model):
    title = models.CharField(max_length=60)
    summary = models.CharField(max_length=200)
    visible = models.BooleanField()
    date_created = models.DateField()
    last_updated = models.DateField()
    
    groups = models.ManyToManyField(OrganizationGroup, through='ExampleGroup')
    user_affiliates = models.ManyToManyField(User, through='UserExample')

    class Meta:
        app_label = 'core_examples'
        
    def __str__(self):
        return self.title

src/dex/models/category.py
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=60, blank=False)
    active = models.BooleanField(default=True)
    required = models.BooleanField(default=False)
    parent_category = models.ForeignKey('self', null=True, blank=True)
    rank = models.IntegerField()
    
    def __unicode__(self):
        return self.name
    
    def __str__(self):
        return self.name

    class Meta:
        app_label = 'dex'
        

src/dex/models/example.py
from dex.models.featurette import Featurette
from dex.models.group import OrganizationGroup
from django.contrib.auth.models import User
from django.db import models
from django.db.models.fields.related import OneToOneField
import comments

class Example(models.Model):
    title = models.CharField(max_length=60, blank=False)
    summary = models.CharField(max_length=200, blank=False)
    visible = models.BooleanField()
    
    date_created = models.DateField('Created', auto_now_add=True)
    last_updated = models.DateField('Updated', auto_now=True)
    
    #groups = models.ManyToManyField(OrganizationGroup, through='ExampleGroup', blank=True)
    user_affiliates = models.ManyToManyField(User, through='UserExample', blank=True)
    featurette = OneToOneField(Featurette, blank=True)
    
    class Meta:
        app_label = 'dex'
        
    def __unicode__(self):
        return self.title
    
    def __str__(self):
        return self.title

comments.register(Example)

class Update(models.Model):
    example = models.ForeignKey(Example)
    updateDate = models.DateField()
    title = models.CharField(max_length=60, blank=False)
    author = models.ForeignKey(User)
    text = models.TextField(max_length=800)
    
    date_created = models.DateField('Created', auto_now_add=True)

comments.register(Update)

src/dex/models/exampleGroup.py
from dex.models.example import Example
from dex.models.group import OrganizationGroup
from django.db import models
'''
Created on Apr 8, 2013

@author: mbianchini
'''

EXAMPLE_GROUP_STATUS = (
    ('PENDING', 'Pending'),
    ('APPROVED', 'Approved'),
    ('DENIED', 'Denied'),
)

class ExampleGroup(models.Model):
    example = models.ForeignKey(Example)
    group = models.ForeignKey(OrganizationGroup)
    
    exampleStatus = models.CharField(max_length=20, null=True, choices=EXAMPLE_GROUP_STATUS) 
    groupStatus = models.CharField(max_length=20, null=True, choices=EXAMPLE_GROUP_STATUS)
    funder = models.BooleanField() 
    
    class Meta:
        app_label = 'dex'

src/dex/models/featurette.py
from django.db import models

class Featurette(models.Model):
    rank = models.IntegerField()
    
    class Meta:
        app_label = 'dex'
        
    def __unicode__(self):
        return self.rank
    
    def __str__(self):
        return "id:" + str(self.id) + " rank:" + self.rank    

src/dex/models/group.py
from dex.models.category import Category
from django.contrib.auth.models import User
from django.db import models
from django.db.models.fields.related import OneToOneField
from dex.models.featurette import Featurette


GROUP_TYPE = (
    ('PRIVATE','Private'),
    ('PUBLIC', 'Public'),
    ('ORGANIZATION', 'Organization'),
)

ORGANIZATION_STATUS = (
    ('PENDING', 'Pending'),
    ('APPROVED', 'Approved'),
    ('DENIED', 'Denied'),
)


class OrganizationGroup(models.Model):
    title = models.CharField(max_length=60, blank=False)
    summary = models.CharField(max_length=200, blank=False)
    group_type = models.CharField(max_length=20, blank=False, choices=GROUP_TYPE)
    allow_join_group = models.BooleanField()
    funder = models.BooleanField()
    date_created = models.DateField('Created', auto_now_add=True)
    last_updated = models.DateField('Updated', auto_now=True)
    org_status = models.CharField(max_length=20, blank=True, choices=ORGANIZATION_STATUS)
    
    user_affiliates = models.ManyToManyField(User, through='UserGroup')  #TODO: validation
    categories = models.ManyToManyField(Category)  #TODO: validation
    featurette = OneToOneField(Featurette, blank=True)

    class Meta:
        app_label = 'dex'
        
    def __unicode__(self):
        return self.title
    
    def __str__(self):
        return "id:" + str(self.id) + " title:" + self.title    

src/dex/models/media.py
from django.db import models
from django.db.models.fields.related import ForeignKey
from dex.models.group import OrganizationGroup
from dex.models.example import Example


class Media(models.Model):
    rank = models.IntegerField()
    
    class Meta:
        app_label = 'dex'
        abstract = True
        
    def __str__(self):
        return "id:" + str(self.id) + " rank:" + str(self.rank)    

class GroupMedia(Media):
    group = ForeignKey(OrganizationGroup) 
    
    class Meta:
        app_label = 'dex'
        
    def __str__(self):
        return super().__str__() 

        
class GroupPhoto(GroupMedia):  
    title = models.CharField(max_length=60)
    photo_file = models.FileField(upload_to='group_photos')  #more appropriately ImageField, but this requires an image lib that isn't yet supported for python 3.3
    
    class Meta:
        app_label = 'dex'
        
    def __str__(self):
        return super().__str__() + " " + self.title  
   
        
class GroupVideo(GroupMedia):
    video_url = models.URLField()
    
    class Meta:
        app_label = 'dex'
        
    def __str__(self):
        return super().__str__() + " " + self.video_url    
    
    
class ExampleMedia(Media):
    example = ForeignKey(Example) 
    
    class Meta:
        app_label = 'dex'
        
    def __str__(self):
        return super().__str__() 

        
class ExamplePhoto(ExampleMedia):  
    title = models.CharField(max_length=60)
    photo_file = models.FileField(upload_to='example_photos')  #more appropriately ImageField, but this requires an image lib that isn't yet supported for python 3.3
    
    class Meta:
        app_label = 'dex'
        
    def __str__(self):
        return super().__str__() + " " + self.title  
   
        
class ExampleVideo(ExampleMedia):
    video_url = models.URLField()
    
    class Meta:
        app_label = 'dex'
        
    def __str__(self):
        return super().__str__() + " " + self.video_url        


src/dex/models/phase.py
'''
Created on Apr 15, 2013

@author: mbianchini
'''
from dex.models.example import Example
from django.db import models

class Phase(models.Model):
    example = models.ForeignKey(Example)

class PhaseAnswer(models.Model):
    phase = models.ForeignKey(Phase)

src/dex/models/profile.py
'''
Created on Apr 8, 2013

@author: mbianchini
'''
from django.contrib.auth.models import User
from django.db import models
from django.db.models.fields.related import OneToOneField
from dex.models.featurette import Featurette

class Profile(models.Model):
    workplace = models.CharField(max_length=200, blank=False)
    department = models.CharField(max_length=200, blank=True)
    city = models.CharField(max_length=100, blank=False)
    state = models.CharField(max_length=20, blank=False)
    biography = models.CharField(max_length=800, blank=False)
    
    date_created = models.DateField('Created', auto_now_add=True)
    last_updated = models.DateField('Updated', auto_now=True)
    
    includeOnAbout = models.BooleanField()
    featurette = OneToOneField(Featurette, null=True)
    
    user = OneToOneField(User)

    class Meta:
        app_label = 'dex'
        
    def __str__(self):
        return self.user.username

src/dex/models/userExample.py
'''
Created on Apr 8, 2013

@author: mbianchini
'''
from dex.models.example import Example
from django.contrib.auth.models import User
from django.db import models

EXAMPLE_AFFILIATION_TYPE = (

    ('ADMIN', 'Administrator'), 
    ('MEMBER', 'Member'),
    ('FOLLOWER', 'Follower'),
    ('INSPIRED_BY', 'Inspired By'),
)


class UserExample(models.Model):
    example = models.ForeignKey(Example)
    user = models.ForeignKey(User)
    
    affiliationType = models.CharField(max_length=20, null=False, choices=EXAMPLE_AFFILIATION_TYPE) 
    
    class Meta:
        app_label = 'dex'

src/dex/models/userGroup.py
'''
Created on Apr 8, 2013

@author: mbianchini
'''
from dex.models.group import OrganizationGroup
from django.contrib.auth.models import User
from django.db import models

class UserGroup(models.Model):
    group = models.ForeignKey(OrganizationGroup)
    user = models.ForeignKey(User)
    
    affiliationType = models.CharField(max_length=20) 
    
    class Meta:
        app_label = 'dex'

src/dex/forms/example.py
'''
Created on Apr 15, 2013

@author: mbianchini
'''
from dex.models.example import Example
from django import forms
from django.contrib.auth.models import User
from django.forms.models import BaseModelFormSet
from django.forms.widgets import HiddenInput

class ExampleForm(forms.ModelForm):
    class Meta:
        model = Example
        exclude = ('user_affiliates', )
        
class BaseUserExampleFormSet(BaseModelFormSet): 
    def add_fields(self, form, index): 
        super(BaseUserExampleFormSet, self).add_fields(form,index) 
        form.fields["user"] = forms.ModelChoiceField(queryset=User.objects.all(), widget=HiddenInput)
        form.fields["example"] = forms.ModelChoiceField(queryset=Example.objects.all(), widget=HiddenInput)
        form.fields["affiliationType"] = forms.CharField(widget=HiddenInput)

src/dex/views/example.py
'''
Created on Apr 8, 2013

@author: mbianchini
'''
from dex.forms.example import ExampleForm, BaseUserExampleFormSet
from dex.models.example import Example
from dex.models.userExample import UserExample
from django.forms.models import  modelformset_factory
from django.shortcuts import get_object_or_404, render, redirect

def show(request, example_id):
    example_instance = get_object_or_404(Example, pk=example_id)
    return render(request, 'dex/example/show.html', {'example_instance': example_instance})

def edit_update(request, example_id):
    example_instance = get_object_or_404(Example, pk=example_id)
    UserExampleFormset = modelformset_factory(UserExample, formset=BaseUserExampleFormSet, extra=1, can_delete=False)
   
    if request.method == 'POST':
        form = ExampleForm(request.POST, instance=example_instance)
        user_formset = UserExampleFormset(request.POST, queryset=UserExample.objects.filter(example=example_instance))
        if (form.is_valid() & user_formset.is_valid()):
            example_instance = form.save()
            user_formset.save()
            return redirect('dex:show', example_instance.id,)
    else :
        form = ExampleForm(instance=example_instance)
        user_formset = UserExampleFormset(queryset=UserExample.objects.filter(example=example_instance))
        
    return render(request, 'dex/example/edit.html', {'example_instance_id': example_instance.id, 'form' : form, 'user_formset' : user_formset})

src/dex/templates/dex/example/browse.html
{% load staticfiles %}

<!-- <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" /> -->

{% if examples %}
    <ul>
    {% for example in examples %}
        <li><a href="{% url 'dex:show' example.id %}">{{ example.title }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No examples are available.</p>
{% endif %}

src/dex/templates/dex/example/edit.html
{% extends "base.html" %}
{% load example_includes %}

{% block title %}Example: {{ example_instance.title }}{% endblock %}

{% block content %}
	 <div role="main">
		<div id="save-panel" class="container_12" style="padding-bottom:20px;">
			<div class="grid_8">
				<h1>Updating your example</h1>
				<p><span id="exampleSubTitle">Click "Finish Editing" when you're done to update your example.</span></p>
			</div>
									
			<div class="grid_4" style="text-align: right;">
				<button id="finish-editing" class="dark" style="margin-top: 26px;">Finish Editing</button>
			</div>
		</div>
		<div class="clear"></div>
	
		<form id="exampleForm" action="{% url 'dex:update' example_instance_id %}" method="post">{% csrf_token %}
			<div class="container_12">
				<div class="grid_8">
					<div class="content-panel example">
	
						<!-- TITLE -->
						<div style="float: left; margin-bottom: 30px;">
							<label for="title"> <span class="required-indicator">*</span>Title<span
								id="title-help" class="help"
								style="float: right; margin-right: 0px;"
								title="Remember you're speaking to a broad audience. So keep it snappy, interesting and jargon-free."></span>
							</label> <span style="color:red;">{{form.title.errors }}</span>
							<input type="text" name="title" maxlength="60"
								value="{{form.title.value}}" style="width: 560px;" />
						</div>
						<div class="clear"></div>
						
						<!--  SUMMARY -->
						<div style="margin-bottom: 30px;">
							<label for="summary"> <span class="required-indicator">*</span>Summary<span
								id="summary-help" class="help"
								style="float: right; margin-right: 5px;"
								title="Give us the quick and dirty on your example - what's it about? Keep it short, there's plenty of places to add more later."></span>
							</label><span style="color:red;">{{form.summary.errors }}</span>
							<input type="text" name="summary" cols="40" rows="3" maxlength="600" 
								value="{{form.summary.value}}" style="width: 560px;" />
						</div>
						
						<!-- VISIBILITY -->
						<label for="visible"> <span class="required-indicator">*</span>Visibility<span
							id="visibility-help" class="help" style="margin-left: 5px;"
							title="Public - Share your idea with the world. Go public! <br/><br/> Private - Not quite ready? Share it with just your team, for now."></span>
						</label><span style="color:red;">{{form.visibility.errors }}</span>
						<div style="margin-bottom: 30px;">
							<div style="float: left; margin-right: 8px;">
								<input type="radio" id="visibilePub" name="visible" value="true"
									{% is_visible form.visible.value %} /> <label
									for="visibilePub"><span></span>Public</label>
							</div>
							<div style="float: left; margin-left: 30px; margin-right: 8px;">
								<input type="radio" id="visibilePri" name="visible" value="false"
									{% is_not_visible form.visible.value %}/> <label
									for="visibilePri"><span></span>Private</label>
							</div>
							<div class="clear"></div>
						</div>
						
						
					</div>
					<div class="clear"></div>
					<div class="clear"></div>
						
					<div id="tab-section" style="margin-top: 30px; margin-left:0px;">
								<!-- <%-- TABS --%> -->
							
								<div id="example-display-tabs" style="margin-left:0px;">
									<div class="grid_8 alpha">
										<ul style="list-style: none; margin: 0px; padding: 0px;">
												<li style="margin-left: 0px; float: left; padding-right: 5px; width:165px;"><a href="#tab-updates" style="text-align:center; width:145px; padding-left:10px; padding-right:10px;">Updates</a></li>
												<li style="margin-left: 10px; float: left; padding-right: 5px; width:165px;"><a href="#tab-phases" style="text-align:center; width:145px; padding-left:10px; padding-right:10px;">Phases</a></li>
												<li id="tabDiscussion" style="margin-left: 10px; float: left; padding-right: 5px; width:165px;"><a href="#tab-discussion" style="text-align:center; width:145px; padding-left:10px; padding-right:10px;">Workspace</a></li>
										</ul>
									</div>
									<div class="clear"></div>
									
									<div id="tab-content" class="grid_8 alpha">
										<div style="margin-left: 20px;">
											
											<!-- <%--  UPDATES --%> -->
											<div id="tab-updates"
												style="margin-left: 0px; margin-right: 0px; padding-left: 0px; padding-top: 0px;;  min-height: 530px  ">
							
												<div
													style="width: 150px; display: inline; float: left; margin-left: 0px;">
													
													<!-- <%-- TIMELINE --%> -->
													<div>
														<ul id="timeline-of-updates" ></ul>
													</div>
													
												</div>
							
												<div 
													style="width:385px; float: left; margin-left: 20px; padding-right: 0px; margin-right: 0px;">
													<div id="update-section" style="margin-bottom:20px"></div>
													<div class="clear"></div>
													<div id="update-comment-section" ></div>
												</div>
											</div>	
					
											
											<!-- <%-- PHASES & DISCUSSION --%> -->
												<div id="tab-phases" class="phase-tabs example"
													style="margin-left: 0px; margin-right: 0px; padding-left: 0px; padding-top: 0px;">
	
													<div id="phase-tabs">
														<ul style="list-style: none; margin-top: 20px; padding: 0px;">
															<li style="margin-left: 0px; float: left; padding-right: 5px; border-right: 1px solid #C9C9C9;"><a href="#tab-seed">Seed</a></li>
															<li style="margin-left: 14px; float: left; padding-right: 5px; border-right: 1px solid #C9C9C9;"><a	href="#tab-sprout">Sprout</a></li>
															<li style="margin-left: 14px; float: left; padding-right: 5px;"><a href="#tab-bloom">Bloom</a></li>
														</ul>
														<!-- <%-- SEED --%> -->
														<g:render template="phaseQuestionsShow" model="${[phase:example_instance.seed, phaseLowerName:'seed', phaseProperName:'Seed', phaseQuestions:seedQuestions, type:ExampleCommentType.SEED, commentCount:seedCommentCount]}" />
														<!-- <%-- SPROUT --%> -->
														<g:render template="phaseQuestionsShow" model="${[phase:example_instance.sprout, phaseLowerName:'sprout', phaseProperName:'Sprout', phaseQuestions:sproutQuestions, type:ExampleCommentType.SPROUT, commentCount:sproutCommentCount]}" />
														<!-- <%-- BLOOM --%> -->
														<g:render template="phaseQuestionsShow" model="${[phase:example_instance.bloom, phaseLowerName:'bloom', phaseProperName:'Bloom', phaseQuestions:bloomQuestions, type:ExampleCommentType.BLOOM, commentCount:bloomCommentCount]}" />
													</div>
												</div>
												
												<div id="tab-discussion"
													style="margin-left: 0px; margin-right: 0px; padding-left: 0px; padding-top: 0px;  min-height: 530px">
													<g:render template="/discussion/discussion" model="${[discussionController:'exampleDiscussion', entityName:'example', entityId:example_instance.id, allowEdit:true]}" />
												</div>
							
										</div>
							
									</div>
									<div class="clear"></div>
								</div>
							
							
							</div>
						
					
				</div>
			
				<div class="grid_4">
						<div style="position: relative; margin-top:25px;" ></div>
					
						<!-- TAGS -->
						<g:if test="${example_instance?.tags}">
							<div id="btn-tags" style="position: relative; margin-bottom: 50px;">
								<h2><g:message code="example.tags.label" /></h2>
								<ul id="tags" class="tags"></ul>
								<div class="clear"></div>
							</div>
						</g:if>
						
						<!-- TEAM -->
							<div id="btn-team" style="position: relative;  margin-bottom: 50px; width:250px;" >
								<h2>Team ({{user_formset.initial_form_count}})</h2>
								{{ user_formset.management_form }}
								<ul id="exTeam" class="team-members">
									{% for form in user_formset.forms %}
										<li><div style="padding:5px 0px 0px 2px;">{{form.instance.user.first_name}}</div></li>
									    {{ form }}
									{% endfor %}
								</ul>
								<div class="clear"></div>	
								<g:if test="${teamCount > 8 }">
									<nav:more action="team"  entityType="${MoreResultsEntityType.EXAMPLE}" entityId="${example_instance.id}" searchId="${example_instance.id}" offset="8" total="${teamCount}" originatorTitle="${example_instance?.title}" />
								</g:if>					
							</div>
						
						<!-- GROUPS -->
						<g:if test="${groups}">
							<div id="btn-groups" style="position: relative;  margin-bottom: 50px; width:250px;" >
								<h2><g:message code="example.groups.label" /> (${groupsCount})</h2>
								<ul id="exGroups" class="example-groups"></ul>
								<div class="clear"></div>	
								<g:if test="${groupsCount > 3 }">
									<nav:more action="groups"  entityType="${MoreResultsEntityType.EXAMPLE}" entityId="${example_instance.id}" searchId="${example_instance.id}" offset="3" total="${groupsCount}" originatorTitle="${example_instance?.title}" />
								</g:if>					
							</div>
						</g:if>
						
						<!-- ORGANIZATIONS -->
						<g:if test="${organizations}">
							<div id="btn-orgs" style="position: relative;  margin-bottom: 50px; width:250px;" >
								<h2><g:message code="example.organizations.label" /> (${organizationsCount})</h2>
								<ul id="exOrgs" class="example-organizations"></ul>
								<div class="clear"></div>	
								<g:if test="${organizationsCount > 2 }">
									<nav:more action="organizations"  entityType="${MoreResultsEntityType.EXAMPLE}" entityId="${example_instance.id}" searchId="${example_instance.id}" offset="2" total="${organizationsCount}" originatorTitle="${example_instance?.title}" />
								</g:if>					
							</div>
						</g:if>
						
						<!-- INSPIRED BY -->
						<g:if test="${inspiredByList}">
							<div id="btn-inspBy" style="position: relative;  margin-bottom: 50px; width:250px;" >
								<h2><g:message code="example.inspiredBy.label" /> (${inspiredByCount})</h2>
								<ul id="exInspBy" class="example-inspirations"></ul>
								<div class="clear"></div>	
								<g:if test="${inspiredByCount > 1 }">
									<nav:more action="inspiredBy"  entityType="${MoreResultsEntityType.EXAMPLE}" entityId="${example_instance.id}" searchId="${example_instance.id}" offset="1" total="${inspiredByCount}" originatorTitle="${example_instance?.title}" />
								</g:if>					
							</div>
						</g:if>
						
						<!-- INSPIRATION FOR -->
						<g:if test="${inspirationFor}">
							<div id="btn-inspFor" style="position: relative;  margin-bottom: 50px; width:250px;" >
								<h2><g:message code="example.inspiration.label" /> (${inspirationForCount})</h2>
								<ul id="exInspFor" class="example-inspirations"></ul>
								<div class="clear"></div>	
								<g:if test="${inspirationForCount > 1 }">
									<nav:more action="inspirationFor"  entityType="${MoreResultsEntityType.EXAMPLE}" entityId="${example_instance.id}" searchId="${example_instance.id}" offset="1" total="${inspirationForCount}" originatorTitle="${example_instance?.title}" />
								</g:if>					
							</div>
						</g:if>
						
						<!-- RELATED EXAMPLES -->
						<g:if test="${relatedExamples}">
							<div id="btn-related" style="position: relative;  margin-bottom: 50px; width:250px;" >
								<h2><g:message code="example.relatives.label" /> (${relatedExamplesCount})</h2>
								<ul id="exRelated" class="example-relatives"></ul>
								<div class="clear"></div>	
								<g:if test="${relatedExamplesCount > 3 }">
									<nav:more action="examples"  entityType="${MoreResultsEntityType.EXAMPLE}" entityId="${example_instance.id}" searchId="${example_instance.id}" offset="3" total="${relatedExamplesCount}" originatorTitle="${example_instance?.title}" />
								</g:if>					
							</div>
						</g:if>
					
					</div>	
			
			</div>
		</form>
	</div>	
	<link rel="stylesheet" type="text/css" href="/static/css/ckdialog.css"/>
	<script type="text/javascript">
		$(document).ready(function(){
			$('#share-dropdown').dropdownmenu({button: 'shareBtn'});
			
			$('#example-display-tabs').tabs();
			$('#phase-tabs').tabs();
			
			$('#finish-editing').on('click', function() {
					var form = $('#exampleForm');
					form.submit();
			});
		});
	</script>	
	<link rel="stylesheet" type="text/css" href="/static/css/ckdialog.css"/>	
{% endblock %}